### ISSUE TITLE
How to insert OpportunityLineItem?

### ISSUE THREAD

**Issue by novumcoder** [Forceea/Forceea-data-factory#179] opened 2021-06-15 12:12 UTC
I fail to insert this because of its double dependancy on Product2Id and PricebookEntryID.

I have this failing code:

```
public static Map < String, FObject > templateOpportunityLineItems() {
    return new Map < String, FObject > {
	'OpportunityLineItems' => new FObject(OpportunityLineItem.SObjectType)
	.setNumberOfRecords(300)
	.setRequiredFields(true)
	.setVerbose(VERBOSE)
	.setDefinition(OpportunityLineItem.Quantity, 'random type(number) from(1) to(10) scale(0)')
	.setDefinition(OpportunityLineItem.TotalPrice, 'random type(number) from(0.5) to(999.99) scale(2)')
	.setDefinition(OpportunityLineItem.PricebookEntryID, 'serial lookup(PricebookEntry) mode(permutation) source(salesforce)')
	.setDefinition(OpportunityLineItem.Product2Id, 'serial lookup(Product2) mode(permutation) source(salesforce)')
	.setDefinition(OpportunityLineItem.OpportunityId, 'serial lookup(Opportunity) mode(cyclical) source(forceea)')

    };
}
```

Error message is: 

Insert failed. First exception on row 0; first error: FIELD_INTEGRITY_EXCEPTION, field integrity exception: PricebookEntryId (pricebook entry is in a different pricebook than the one assigned to the opportunity): [PricebookEntryId].

**Comment by nmitrakis** [comment] 2021-06-15 12:15
Let me check it.

**Comment by nmitrakis** [comment] 2021-06-15 16:05
We have 2 scenarios here:

**A. Create records in an org**

Assumptions: our org contains opportunities, products, price books (active) and price book entries.

Script:
```
public static Map <String, FObject> templateOpportunityLineItems() {
	return new Map <String, FObject>{
		'OpportunityLineItems' => new FObject(OpportunityLineItem.SObjectType, 300)
			.setDefinition(OpportunityLineItem.Quantity, 'random type(number) from(1) to(10) scale(0)')
			.setDefinition(OpportunityLineItem.Description, 'random type(text) minLength(20) maxLength(40)')
			.setDefinition(OpportunityLineItem.PricebookEntryID, 'serial lookup(PricebookEntry) mode(cyclical) source(salesforce)')
			.setDefinition(OpportunityLineItem.OpportunityId, 'serial lookup(Opportunity) mode(cyclical) source(salesforce)')
	};
}
FObject.insertRecordsFromTemplate(templateOpportunityLineItems(), true);
```
This script creates values for the Description field (optional).
We don't use the TotalPrice and Product2Id fields.
See https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_opportunitylineitem.htm

**B. Create records in a test method**

You have to create opportunities, products, price books and price book entries before you create OpportunityLineItem records.
- For the opportunities and products, I assume they are trivial.
- For the price book and price book entries: Forceea provides an easy way to handle the standard price book and its entries.

```
public static Map<String, FObject> templatProducts() {
	return new Map<String, FObject>{
		'Products' => new FObject(Products2.SObjectType, NUM_PRODUCTS) // privatestatic final String NUM_PRODUCTS = 5;
                    .setRequiredFields(true) // not a best practice to use it
                    .setDefinition(Product2.Name, 'static value("Product-")')
                    .setDefinition(Product2.Name, 'serial type(number) from(1) step(1) scale(0)')
                    .setDefinition(Product2.Description, 'random type(text) minLength(25) maxLength(50)')
                    .setDefinition('$StandardPrice', 'random type(number) from(10) to(100) scale(2)')
                    .setStandardPricebookEntries('$StandardPrice');
	};
}
```
The method `setStandardPricebookEntries` Inserts the entries for the active Standard Price Book and uses the values of a virtual field to populate the field List Price (UnitPrice) of the PricebookEntry SObject (see Forceea Success Guide page 119).

Now your template would be:
```
public static Map<String, FObject> templateOpportunityLineItems() {
	return new Map<String, FObject>{
		'OpportunityLineItems' => new FObject(OpportunityLineItem.SObjectType, 300)
	            .setDefinition(OpportunityLineItem.Quantity, 'random type(number) from(1) to(10) scale(0)')
	            .setDefinition(OpportunityLineItem.Description, 'random type(text) minLength(20) maxLength(40)')
	            .setDefinition(OpportunityLineItem.PricebookEntryID, 'serial lookup(PricebookEntry) mode(cyclical) source(forceea)')
	            .setDefinition(OpportunityLineItem.OpportunityId, 'serial lookup(Opportunity) mode(cyclical) source(forceea)') // not salesforce
	};
}
```
You could combine all this into your test method as follows:
```
Map<String, FObject> template = new Map<String, FObject>();
template.putAll(DataFactory.templateOpportunities());
template.putAll(DataFactory.templatProducts());
template.putAll(DataFactory.templateOpportunityLineItems());
FObject.insertRecordsFromTemplate(template, true);
```

**Some general notes**: we can use **permutations** (`mode(permutation)`) when we want "for each opportunity and for each product (related to a price book entry) to insert an opportunity line item, which is an absolutely valid business scenario (in fact I do recommend it). In this case, the script for the OLI template could be:
```
'OpportunityLineItems' => new FObject(OpportunityLineItem.SObjectType)
    .setNumberOfRecords('auto') // this means that Forceea will "find" the number of records from the number of combinations
    .setDefinition(OpportunityLineItem.Quantity, 'random type(number) from(1) to(10) scale(0)')
    .setDefinition(OpportunityLineItem.Description, 'random type(text) minLength(20) maxLength(40)')
    .setDefinition(OpportunityLineItem.PricebookEntryID, 'serial lookup(PricebookEntry) mode(permutation) source(forceea)')
    .setDefinition(OpportunityLineItem.OpportunityId, 'serial lookup(Opportunity) mode(permutation) source(forceea)')
```

And finally some general best practices:
- Use `FObject.setGlobalVerbose('debug');` in the first line of your test method to see the generation process, and remove it when you finish development.
- Use constants for the number of records or the map keys, e.g. OPPORTUNITY_LINE_ITEMS instead of 'OpportunityLineItems'.

I hope I helped a little bit.

**Comment by novumcoder** [comment] 2021-06-15 18:51
Thanks for the info, but im still getting the same issue after adaption to your solution. Check my entrie apex class doing the job which is failing for OpportunityLineItem. Anything missing here? Im running the run Method with async=true and iterations=1
[Helper.zip](https://github.com/Forceea/Forceea-data-factory/files/6657974/Helper.zip)
@nmitrakis

**Comment by nmitrakis** [comment] 2021-06-16 11:13
The method `setStandardPricebookEntries` is not supported from FObjectAsync at the moment (see Success Guide p.77 for the supported FObject methods on the asynchronous process). It will probably be a feature of v2.5.

So, how do we handle this now?

- Confirm that the Standard Price Book is **active**.
- Execute the method `Helper.insertProducts()`
- Execute the method `Helper.run()`

The changes I've done in your class (the records are created successfully) have the following logic:
- Insert Products and Pricebook entries synchronously, before the asynchronous process
- Insert all other records asynchronously

The reason behind this decision is that we may create millions of opportunities, but we don't want millions of products. In this way, we successfully combine both sync and async processes.

Regarding your class:
- Added some template key and number of records constants.
- Removed the `setVerbose` every template - use `FObject.setGlobalVerbose` once.
- Added the method `deleteRecords` which deletes all SObjects included in the template asynchronously. It's very useful to "erase" the old data. 
- Added `setVariable` method on Opportunities.
- Used permutations in `templateOpportunityLineItems`. At the moment setNumberOfRecords('auto') is not supported in the async process (will be in v2.6), so I manually calculated the number of records (1000 = 10 products x 100 opportunities).
- Removed some fields from `templateCampaignMembers`

Pay attention to the fields you use in `setPartitionFieldName`; they must be editable. For example, the Description field in CampaignMembers is not. There are similar fields in other templates as well. Additionally, all SObjects must have a partition field in order to delete records using partitions (much faster).

You can watch the async process from the Forceea app.

[Helper.zip](https://github.com/Forceea/Forceea-data-factory/files/6662527/Helper.zip)

**Comment by nmitrakis** [comment] 2021-06-17 07:52
In Setup > Opportunity Settings select both options. Otherwise Salesforce will ask for TotalPrice on OLI records.

**Comment by novumcoder** [comment] 2021-06-17 16:14
Hey thanks @nmitrakis for all the info. I still tried to insert all and do not care much about deleting and partitionFields. But the product part is still failing for me. I'm getting 

**STANDARD_PRICE_NOT_DEFINED, Before creating a custom price, create a standard price.: []**

only for running this


```
public static void insertProducts() {
	FObject.setGlobalVerbose(VERBOSE);

	Map<String, FObject> template = new Map<String, FObject> ();
	template.putAll(templateProducts());
	FObject.insertRecordsFromTemplate(template, true);
	template.clear();
	template.putAll(templatePricebookEntries());
	FObject.insertRecordsFromTemplate(template, true);
}
```
I inserting seperately because i was wondering if it first needs the product in db, then add the entries, but no luck.

But since it is adding Product2 it should assign it to the standard price book right? Was this working for you?

**Comment by nmitrakis** [comment] 2021-06-17 16:30
Yes the script works for me. It can be simplified as
```
Map<String, FObject> template = new Map<String, FObject> ();
template.putAll(templateProducts());
template.putAll(templatePricebookEntries());
FObject.insertRecordsFromTemplate(template, true);
```

As I mentioned in my previous notes, you must confirm that you have an **active** Standard price book. By default, there is a price book called `Standard Price Book` which is inactive, so you should activate it. Pay attention to the name in `templatePricebookEntries` - it should read `static lookup(Pricebook2) field(Name) value(Standard Price Book) source(salesforce)')`. If your Standard Price Book's name is different, you have to modify the script.

From the error message I assume you try to insert the Products (which should be successful) and then you insert the price book entries, which fails. The reason is that your Standard price book is inactive or has a different Name, so you actually try to insert records to "another" price book. Correct your Standard Price Book and retry.

**Comment by novumcoder** [comment] 2021-06-18 17:06
Ok got it, but i have a strange setting on the two records. One active but not standard, the other standard but not active. Tried to fetch the active one and make it Standard, but that field is not writable. Any idea how i get this solved?

![image](https://user-images.githubusercontent.com/6917790/122594092-da248480-d066-11eb-8071-55a2bd0627ef.png)

What is wrong on this code, i followed your suggestions.
![image](https://user-images.githubusercontent.com/6917790/122595129-418f0400-d068-11eb-9efc-fff8819fa19d.png)

@nmitrakis

**Comment by nmitrakis** [comment] 2021-06-18 19:31
1. Edit the price book with the name `Standard Price Book` and set it as `Active`. This should be straightforward. Now you should have your active standard price book.

2. The problem with the code is the definition of `PricebookEntry.Pricebook2Id`. The definition `random lookup` will get a random price book. You have 2 price books and one of them is inactive. You don't mention what is the issue, but I guess it's because of this inactive price book (with name = "Standard Price Book").

To remedy the issue I would use the definition `static lookup(PriceBook2) field(Name) value(Standard Price Book) source(salesforce)`. This should get only this specific price book and would work, given that you have activated it (step 1).

Let me know if it worked.

**Comment by nmitrakis** [comment] 2021-06-18 20:38
A simpler solution would be:
```
public static Map<String, FObject> templatProducts() {
	return new Map<String, FObject>{
		'Products' => new FObject(Products2.SObjectType, NUM_PRODUCTS)
                    .setDefinition(Product2.Name, 'static value("Product-")')
                    .setDefinition(Product2.Name, 'serial type(number) from(1) step(1) scale(0)')
                    .setDefinition(Product2.Description, 'random type(text) minLength(25) maxLength(50)')
                    .setDefinition('$StandardPrice', 'random type(number) from(10) to(100) scale(2)')
                    .setStandardPricebookEntries('$StandardPrice');
	};
}
```
This template can be used with `Fobject.insertRecordsFromTemplate(templatProducts(), true)` to insert products **and** price book entries on the standard price book. Note: again, the standard price book should be active.

**Comment by nmitrakis** [comment] 2021-06-19 16:34
A correction: the Helper class includes a `deleteRecords` method, which won't work with multiple jobs, as it doesn't provide the Partition Field.  Please change it to the following snippet:
```
Map<String, FObject> template = templateAll();
template.get(ACCOUNTS).setPartitionFieldName(Account.AccountSource);
template.get(OPPORTUNITIES).setPartitionFieldName(Opportunity.NextStep);

new FObjectAsync(template)
    .setNumberOfJobs(50)
    .setPartitionFieldValue('demo')
    .deleteRecords();
}
```
The `numberOfJobs `should be equal or less than the `numberOfJobs `when you inserted the records (as a best practice set it equal).

It's always better to include the `setPartitionFieldName` into your template.

**Comment by nmitrakis** [comment] 2021-06-22 14:12
If the problem is solved, please let me know to close the issue. @novumcoder

**Comment by novumcoder** [comment] 2021-06-22 18:58
@nmitrakis Ok thanks, got it working for the products. Now it seems to run, but the UI only shows me something about optimizing performance, but on the apex log i see this:

20:53:20:191 USER_DEBUG [2782]|ERROR|FORCEEA FORCEEA * Invalid number of records of [Account].
20:53:20:193 FATAL_ERROR FObject.FObjectException: Process is invalid and will terminate.

![image](https://user-images.githubusercontent.com/6917790/122983731-98644880-d39c-11eb-8477-1a5f94baf40b.png)

Whats wrong with account definition. I got this one from your changed apex class.

**Comment by nmitrakis** [comment] 2021-06-22 21:16
The error message "Invalid number of records of.." is displayed when we initialize an FObject instance with numberOfRecords < 0. The attached snippet doesn't have any error.

Additionally the Helper class I attached previously (which you mentioned you used) is executed successfully in my org (with Forceea v.2.4).
- Please confirm you use the latest version v.2.4. If not, install the latest version and execute your code again.
- If you use v.2.4, please send your Helper class to nikos@acmantics.gr.

I feel that you are close to make the script run, but let's continue this conversation offline, and finally put the solution here, so other users get some more insight.

**Comment by nmitrakis** [comment] 2021-07-02 11:15
@novumcoder Please close the issue if it is solved. If not, let me know what is pending. As we discussed offline, the code should work.

**Comment by nmitrakis** [comment] 2021-07-06 13:15
@novumcoder Since there is no response from your side, I'll consider the issue closed.

**Closed as completed** 2021-07-06 13:15 UTC
Labels: question

**Comment by novumcoder** [comment] 2021-07-06 18:05
Hi sorry. Yea its now running fine. I had to add the batch limit, because for some reason it was not able to "optimize" according to the log. But thats fine. This way i was able to create tons of records. Thanks for your time and help @nmitrakis.

**Comment by nmitrakis** [comment] 2021-07-06 18:22
I'm glad it worked. The new release v2.5 added some smart handling of asynchronous deletion errors when we have cascade delete, for example when you delete Opportunities after deleting Line Items. You can exclude some (child) SObjects from deletion as well.
